- name: instal and run nginx
  hosts: web
  become: yes # we will get root access
  tasks: 
  - name: install nginx package
    ansible.builtin.package:
      name: ntpdate
      state: present
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started

