- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ course }}, learner is {{ learner }}, duration is {{ duration }}"
