- name: Variables from PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  # vars_prompt:
  # - name: PERSON
  #   prompt: please enter your name
  #   private: false # user can see what they are entering
  # - name: WISHES
  #   prompt: please enter your wishes
  #   private: true # user can't see what they are entering
  vars:
    PERSON: " guru from play"
    WISHES: "Morning from play"
  tasks:
    - name: Check variables
      # vars:
      #   PERSON: " guru from play"
      #   WISHES: "Morning from play"
      ansible.builtin.debug:
        msg: "Hello {{ PERSON }}, Good {{ WISHES }}"

#1. cmd
#2. task
#3. files
#4.prompt