
- name: loops
  hosts: localhost 
  become: yes 
  tasks:  
  - name: print persons
    ansible.builtin.packages:
      name: "{{item}}"
      status: present
    loop:
      - git
      - mysql 
      - postfix


