- name: loops
  hosts: localhost
  become: yes  # Use 'become' to gain elevated privileges, if required
  tasks:
  - name: ensure packages are installed
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - mysql
      - postfix




